services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub-project2
    ports:
      - "5555:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome-node-project2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-project2
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:latest
    container_name: edge-node-project2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-project2
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
